"""add checksums

Revision ID: 7a7422f19234
Revises: 818bfb535590
Create Date: 2019-02-06 09:54:03.138950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7422f19234'
down_revision = '818bfb535590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_global', sa.Column('sha256', sa.String(), nullable=True))
    op.add_column('frames', sa.Column('sha256', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frames', 'sha256')
    op.drop_column('file_global', 'sha256')
    # ### end Alembic commands ###
