"""change s3 to storage dir

Revision ID: 8e0d2514fd1f
Revises: bae28d7da970
Create Date: 2019-09-16 08:47:36.800607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0d2514fd1f'
down_revision = 'bae28d7da970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_global', sa.Column('storage_dir', sa.String(), nullable=True))
    op.drop_column('file_global', 's3_dir')
    op.add_column('frames_global', sa.Column('storage_dir', sa.String(), nullable=True))
    op.drop_column('frames_global', 's3_dir')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frames_global', sa.Column('s3_dir', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('frames_global', 'storage_dir')
    op.add_column('file_global', sa.Column('s3_dir', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file_global', 'storage_dir')
    # ### end Alembic commands ###
