"""added file name to file_global

Revision ID: bae28d7da970
Revises: 7a7422f19234
Create Date: 2019-04-15 14:31:47.880557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae28d7da970'
down_revision = '7a7422f19234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_global', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_global', 'file_name')
    # ### end Alembic commands ###
